pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages {
        stage('Init Provider') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Plan resource') {
            steps {
                sh 'terraform plan'
            }
        }
        stage('Apply resource') {
            inputs {
                message "Do you want to process for production deployment?"
            }
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}


}